/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./pages/__root"
import { Route as IndexImport } from "./pages/index"
import { Route as ScoutingIndexImport } from "./pages/scouting.index"
import { Route as ScoutingFormPageImport } from "./pages/scouting.$formPage"

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const ScoutingIndexRoute = ScoutingIndexImport.update({
  path: "/scouting/",
  getParentRoute: () => rootRoute,
} as any)

const ScoutingFormPageRoute = ScoutingFormPageImport.update({
  path: "/scouting/$formPage",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/scouting/$formPage": {
      preLoaderRoute: typeof ScoutingFormPageImport
      parentRoute: typeof rootRoute
    }
    "/scouting/": {
      preLoaderRoute: typeof ScoutingIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ScoutingFormPageRoute,
  ScoutingIndexRoute,
])

/* prettier-ignore-end */
